// get all accounts
GET http://localhost:4400/api/v1/account


###
// create new token account
POST http://localhost:4400/api/v1/account
Content-Type: application/json



###
// create a new account 
POST http://localhost:4400/api/v1/account
Content-Type: application/json

###
// transfer VRT
POST http://localhost:4400/api/v1/transaction/transfer
Content-Type: application/json

{
  "senderPublicKey": "CQyz1ZBJ4jvZuTCC9KB2yRzU5R4V53b9n8sf8uCFsY2h", 
  "recipientPublicKey": "C8vSQ2VamRTkZPMvHKc71bP4owbuLDMrnRHK2oSLnjLV", 
  "amount": "2", 
  "privateKey": "h5ZoEaUXsPP3WNNi3GugVM7TpuLpCZcvACuEyX9PHoZ9mLgjpATsk7Vz3emByVtSmVVKToVUApxDouQ62zMCuPi"
}

###
// get account info from seed phrase
POST http://localhost:4400/api/v1/account/getAccount
Content-Type: application/json

{
  "seedPhrase": "prefer donkey release pelican poverty air column angry circle soft fetch sunset"
}



###
// get balance
GET http://localhost:4400/api/v1/account/getBalance/CQyz1ZBJ4jvZuTCC9KB2yRzU5R4V53b9n8sf8uCFsY2h

###
// add VRT to db 
POST http://localhost:4400/api/v1/vrt
Content-Type: application/json

###
// freeze VRT
POST http://localhost:4400/api/v1/vrt/freeze/VRT
Content-Type: application/json

###
// unfreeze VRT
POST http://localhost:4400/api/v1/vrt/unfreeze/VRT
Content-Type: application/json

###
// airdrop VRT 
POST http://localhost:4400/api/v1/vrt/airdrop
Content-Type: application/json

{
  "publicKey": "CQyz1ZBJ4jvZuTCC9KB2yRzU5R4V53b9n8sf8uCFsY2h"
}

###
// register new gamer
POST http://localhost:4400/api/v1/gamer/signup
Content-Type: application/json

{
  "gamerTag": "vince",
  "email": "vincentcornelius489@gmail.com",
  "password": "12345678"
}


###
// get all seed phrases
GET http://localhost:4400/api/v1/seedPhrase

###
// get all blocks
GET http://localhost:4400/api/v1/block

###
// create a new block
POST http://localhost:4400/api/v1/block
Content-Type: application/json

###
// create genesis block
POST http://localhost:4400/api/v1/block/genesis
Content-Type: application/json

###
//get all transactions
GET http://localhost:4400/api/v1/transaction


###
// transfer VRT
POST http://localhost:4400/api/v1/transaction/transfer
Content-Type: application/json

{
  "senderPublicKey": "CQyz1ZBJ4jvZuTCC9KB2yRzU5R4V53b9n8sf8uCFsY2h", 
  "recipientPublicKey": "C8vSQ2VamRTkZPMvHKc71bP4owbuLDMrnRHK2oSLnjLV", 
  "amount": 2, 
  "privateKey": "h5ZoEaUXsPP3WNNi3GugVM7TpuLpCZcvACuEyX9PHoZ9mLgjpATsk7Vz3emByVtSmVVKToVUApxDouQ62zMCuPi"
}


###
// updat a fighter's stats
PUT http://localhost:4400/api/v1/fighter/:id
Content-Type: application/json

{
  "wins": 1,
  "losses": 0,
  "draws": 0,

}

###
// create new gaming token
POST http://localhost:4400/api/v1/token
Content-Type: application/json

{
    "address":"bRT1jCHNK5nb46R4tpkhgVX7GnwMTrSLZTfrxacpHACP",
    "uri":"https://virtronesports.com/img/IBFBelt.png",
    "symbol": "BNV",
    "name": "Boxing Nation Virtron",
    "mintAuthority": "7T6C4Es9QhcWMEVXvPpsnyzvrPj2SYUVvhgF49wRYg2e",
    "freezeAuthority": "7T6C4Es9QhcWMEVXvPpsnyzvrPj2SYUVvhgF49wRYg2e",
    "supply": "1000000000",
    "balance": "1000000000",
    "type": "Gaming Token"
  }






