// get all accounts
GET http://localhost:4400/api/v1/account


###
// create a new account 
POST http://localhost:4400/api/v1/account/
Content-Type: application/json

###
// transfer VRT
POST http://localhost:4400/api/v1/account/transfer
Content-Type: application/json

{
  "senderPublicKey": "2DEPhPfrBUZ5ZdJAVwXE6MUssx5aFL5LSCvtZyw19FwA", 
  "recipientPublicKey": "78ev7UqLj2trzZYRUKQsADhHPX42rV8CeXCwhQVta7nb", 
  "amount": "25", 
  "privateKey": "h5ZoEaUXsPP3WNNi3GugVM7TpuLpCZcvACuEyX9PHoZ9mLgjpATsk7Vz3emByVtSmVVKToVUApxDouQ62zMCuPi"
}

###
// get account info from seed phrase
POST http://localhost:4400/api/v1/account/getAccount
Content-Type: application/json

{
  "seedPhrase": "sea minute notice else renew absurd bonus caught bird garage kit poem"
}

###
// get balance
GET http://localhost:4400/api/v1/account/getBalance/4UpxViZy6ENFijvn3MfYfyAKLsTkHj1gJQaeUQMvqHY5

###
// add VRT to db 
POST http://localhost:4400/api/v1/vrt
Content-Type: application/json

###
// freeze VRT
POST http://localhost:4400/api/v1/vrt/freeze/VRT
Content-Type: application/json

###
// unfreeze VRT
POST http://localhost:4400/api/v1/vrt/unfreeze/VRT
Content-Type: application/json

###
// airdrop VRT 
POST http://localhost:4400/api/v1/vrt/airdrop
Content-Type: application/json

{
  "publicKey": "GPBnBmPMocU5LezMp5oz167RyLUTD6xk6do4H7vPbFVC"
}

###
// register new gamer
POST http://localhost:4400/api/v1/gamer/signup
Content-Type: application/json

{
  "gamerTag": "vince",
  "email": "vincentcornelius489@gmail.com",
  "password": "12345678"
}

###
// add account to gamer
POST http://localhost:4400/api/v1/gamer/add-account
Content-Type: application/json

{
  "gamerTag": "Marvin",
  "accountId": "651c52a6758d5be0fef7b571"
}



###
// get all seed phrases
GET http://localhost:4400/api/v1/seedPhrase

###
// get all blocks
GET http://localhost:4400/api/v1/block

###
// create a new block
POST http://localhost:4400/api/v1/block
Content-Type: application/json

###
// create genesis block
POST http://localhost:4400/api/v1/block/genesis
Content-Type: application/json


###
// transfer VRT
POST http://localhost:4400/api/v1/transaction/transfer
Content-Type: application/json

{
  "senderPublicKey": "4UpxViZy6ENFijvn3MfYfyAKLsTkHj1gJQaeUQMvqHY5", 
  "recipientPublicKey": "78ev7UqLj2trzZYRUKQsADhHPX42rV8CeXCwhQVta7nb", 
  "amount": 10, 
  "privateKey": "h5ZoEaUXsPP3WNNi3GugVM7TpuLpCZcvACuEyX9PHoZ9mLgjpATsk7Vz3emByVtSmVVKToVUApxDouQ62zMCuPi"
}






