// get all accounts
GET http://localhost:4400/api/v1/account 


###
// create a new account 
POST http://localhost:4400/api/v1/account
Content-Type: application/json

###
// get account info from seed phrase
POST http://localhost:4400/api/v1/account/getAccount
Content-Type: application/json

{
  "seedPhrase": "prefer donkey release pelican poverty air column angry circle soft fetch sunset"
}



###
// get balance
GET http://localhost:4400/api/v1/account/getBalance/7VaGyYw7LAuFgEy9YCDb1dSjNfo5FwvhmbzBU81KYwU8

###
// add VRT to db 
POST http://localhost:4400/api/v1/vrt
Content-Type: application/json

###
// freeze VRT
POST http://localhost:4400/api/v1/vrt/freeze/VRT
Content-Type: application/json

###
// unfreeze VRT
POST http://localhost:4400/api/v1/vrt/unfreeze/VRT
Content-Type: application/json

###
// airdrop VRT 
POST http://localhost:4400/api/v1/vrt/airdrop2
Content-Type: application/json

{
  "amount": 20000,
  "publicKey": "Yb5QR4vog5Ep8m46PSWkYB5oWDSQmkNQukK2YSpvoiP"
}

###
// register new gamer
POST http://localhost:4400/api/v1/gamer/signup
Content-Type: application/json

{
  "gamerTag": "vince",
  "email": "vincentcornelius489@gmail.com",
  "password": "12345678"
}


###
// get all seed phrases
GET http://localhost:4400/api/v1/seedPhrase

###
// get all blocks
GET http://localhost:4400/api/v1/block

###
// create a new block
POST http://localhost:4400/api/v1/block
Content-Type: application/json


###
//get all transactions
GET http://localhost:4400/api/v1/transaction


###
// transfer VRT
POST http://localhost:4400/api/v1/transaction/transfer
Content-Type: application/json

{
  "senderPublicKey": "HA8gBN4rcspRtg1148CM4aLe55ZikiX3ZcL5JDPzmtjT", 
  "recipientPublicKey": "992PcfcepEDhq6KggXkEYBvBmYgWebEH1KPtkAVzgjy4", 
  "amount": 23
}

###
// Get transaction by id

GET http://localhost:4400/api/v1/transaction/6541067af67fdb0dd70062dc



###
// update a fighter's stats
PUT http://localhost:4400/api/v1/fighter/:id
Content-Type: application/json

{
  "wins": 1,
  "losses": 0,
  "draws": 0,

}

###
// create new gaming token
POST http://localhost:4400/api/v1/token
Content-Type: application/json

{
    "uri":"https://virtronesports.com/img/IBFBelt.png",
    "symbol": "BiNV",
    "name": "Boxing Naition Virtron",
    "decimals": 6,
    "mintAuthority": "7T6C4Eis9QhcWMEVXvPpsnyzvrPj2SYUVvhgF49wRYg2e",
    "freezeAuthority": "7T6C4iEs9QhcWMEVXvPpsnyzvrPj2SYUVvhgF49wRYg2e",
    "totalSupply": 1000000000,
    "type": "Gaming Token"
  }

###
// create new token account
POST http://localhost:4400/api/v1/tokenAccount
Content-Type: application/json

{
  "mint": "51o2CpyyrmAsC2tiFRNWr56aLb4SW5sApcLMzrtSYmZX",
  "owner": "654295691209ceec11cb281a"
}

###
// create new token account
POST http://localhost:4400/api/v1/tokenAccount/add-token-account
Content-Type: application/json

{
  "mint": "51o2CpyyrmAsC2tiFRNWr56aLb4SW5sApcLMzrtSYmZX",
  "owner": "654295691209ceec11cb281a"
}


###
// Add token account to gamer account
POST http://localhost:4400/api/v1/tokenAccount/associate-token-account
Content-Type: application/json

{
  "accountId": "654295691209ceec11cb281a",
  "tokenAccountId": "6542a043e30ecf7cec384fa4"
}






