// Get all gamers
GET http://localhost:4400/api/v1/gamer

###
// Add tokenAccount to gamer
POST http://localhost:4400/api/v1/tokenAccount/add-token-account
Content-Type: application/json

{
  "gamerTag": "johnny",
  "mint": "51o2CpyyrmAsC2tiFRNWr56aLb4SW5sApcLMzrtSYmZX"
}

###
// Add account to gamer
POST http://localhost:4400/api/v1/gamer/add-gamer
Content-Type: application/json

{
  "gamerTag": "johnny",
  "email": "johnny@aol.com",
  "password": "password"
}

###
// signup
POST http://localhost:4400/api/v1/gamer/signup
Content-Type: application/json

{
  "gamerTag": "Lamar",
  "email": "lamaranthonyholdings@gmail.com",
  "password": "12345678"
}

###
// verify email
POST http://localhost:4400/api/v1/email_verification/verify
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com",
  "otp": "4292"
}

###
// login
POST http://localhost:4400/api/v1/gamer
Content-Type: application/json

{
  "gamerTag": "Lamar",
  "password": "12345678"
}

###
// forgot password
POST http://localhost:4400/api/v1/forgot_password/
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com"
}

###
// Password reset
POST http://localhost:4400/api/v1/forgot_password/reset
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com",
  "otp": "3446",
  "newPassword": "12345678"
}

###
// Request new OTP
POST http://localhost:4400/api/v1/otp/request-new-otp
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com"
}

###
// add account to gamer
POST https://test-virtue-production.up.railway.app/api/v1/gamer/add-account
Content-Type: application/json

{
  "gamerTag": "Me",
  "accountId": "652754987ca684c9008cd21c"
}


###
POST http://localhost:4400/api/v1/tokenAccount
Content-Type: application/json

{
  "mint": "0x000000",
  "owner": "65412708a07c37ea474d57f1"
}
