POST http://localhost:4400/api/v1/stake
Content-Type: application/json

{
    "stakerPublicKey": "69FweEAamf9FbEAHYR9pM4ee8mRpzwM2SmYnCvGHF1dK",
    "amount": 100,
    "lockupPeriod": 592001
}

###
// Validate the transaction
GET http://localhost:4400/api/v1/validator/select-validators
